Repository SWM-IDLE/mybrary-application, pull requests merged in 2023-09, with the labels that each got.

#1 [IDLE-236] refactor: 홈 화면 리팩토링 및 캐싱 적용
  app-ui/android/app/build.gradle
  app-ui/ios/.gitignore
  app-ui/ios/Flutter/Release.xcconfig
  app-ui/ios/Runner.xcodeproj/project.pbxproj
  app-ui/ios/Runner/GoogleService-Info.plist
  app-ui/lib/data/datasource/home/home_datasource.dart
  app-ui/lib/data/model/common/books_params.dart
  app-ui/lib/data/model/common/books_params.g.dart
  app-ui/lib/data/model/common/common_model.dart
  app-ui/lib/data/model/common/common_model.g.dart
  app-ui/lib/data/model/home/book_list_by_category_response.dart
  app-ui/lib/data/model/home/book_recommendations_response.dart
  app-ui/lib/data/model/home/books_by_category_model.dart
  app-ui/lib/data/model/home/books_by_category_model.g.dart
  app-ui/lib/data/model/home/books_by_interest_model.dart
  app-ui/lib/data/model/home/books_by_interest_model.g.dart
  app-ui/lib/data/model/home/today_registered_book_count_model.dart
  app-ui/lib/data/model/home/today_registered_book_count_model.g.dart
  app-ui/lib/data/network/api.dart
  app-ui/lib/data/provider/common/dio_provider.dart
  app-ui/lib/data/provider/common/secure_storage_provider.dart
  app-ui/lib/data/provider/home/home_bestseller_provider.dart
  app-ui/lib/data/provider/home/home_provider.dart
  app-ui/lib/data/provider/home/home_recommendation_books_provider.dart
  app-ui/lib/data/provider/user_provider.dart
  app-ui/lib/data/repository/home_new_repository.dart
  app-ui/lib/data/repository/home_new_repository.g.dart
  app-ui/lib/data/repository/home_repository.dart
  app-ui/lib/main.dart
  app-ui/lib/res/variable/global_navigator_variable.dart
  app-ui/lib/ui/auth/sign_in/sign_in_screen.dart
  app-ui/lib/ui/common/components/sliver_loading.dart
  app-ui/lib/ui/home/components/home_best_seller.dart
  app-ui/lib/ui/home/components/home_interest_setting_button.dart
  app-ui/lib/ui/home/components/home_intro.dart
  app-ui/lib/ui/home/components/home_recommend_books.dart
  app-ui/lib/ui/home/components/home_recommend_books_header.dart
  app-ui/lib/ui/home/home_screen.dart
  app-ui/lib/ui/mybook/interest_book_list/interest_book_list_screen.dart
  app-ui/lib/ui/mybook/mybook_detail/components/mybook_edit_review.dart
  app-ui/lib/ui/mybook/mybook_detail/mybook_detail_screen.dart
  app-ui/lib/ui/mybook/mybook_list/mybook_list_screen.dart
  app-ui/lib/ui/mybook/mybook_screen.dart
  app-ui/lib/ui/profile/follow/follow_screen.dart
  app-ui/lib/ui/profile/my_interests/my_interests_screen.dart
  app-ui/lib/ui/profile/profile_edit/profile_edit_screen.dart
  app-ui/lib/ui/profile/profile_screen.dart
  app-ui/lib/ui/search/search_book_list/search_book_list.dart
  app-ui/lib/ui/search/search_detail/components/book_detail_header.dart
  app-ui/lib/ui/search/search_detail/search_detail_screen.dart
  app-ui/lib/ui/search/search_detail_review/components/review_item.dart
  app-ui/lib/ui/search/search_detail_review/search_detail_review_screen.dart
  app-ui/lib/ui/setting/components/account_withdrawal.dart
  app-ui/pubspec.lock
  app-ui/pubspec.yaml
Labels: refactor

#3 [Hotfix] sonar cloud 설정
  .github/workflows/application-code-analytics.yml
  app-ui/sonar-project.properties
Labels: hotfix, cicd

#4 [Hotfix] sonar cloud 설정
  sonar-project.properties
Labels: hotfix, cicd

#5 [Hotfix] sonar cloud bug 수정
  .github/workflows/application-code-analytics.yml
  app-ui/sonar-project.properties
Labels: hotfix, cicd

#2 [IDLE-256] feat&fix: 자잘한 기능 수정과 구현
  app-ui/lib/data/datasource/book/book_datasource.dart
  app-ui/lib/data/repository/book_repository.dart
  app-ui/lib/res/constants/config.dart
  app-ui/lib/res/constants/style.dart
  app-ui/lib/ui/auth/sign_in/sign_in_screen.dart
  app-ui/lib/ui/home/home_screen.dart
  app-ui/lib/ui/mybook/interest_book_list/interest_book_list_screen.dart
  app-ui/lib/ui/mybook/mybook_detail/components/mybook_detail_record.dart
  app-ui/lib/ui/mybook/mybook_detail/components/mybook_detail_review.dart
  app-ui/lib/ui/mybook/mybook_detail/components/mybook_edit_review.dart
  app-ui/lib/ui/mybook/mybook_detail/mybook_detail_screen.dart
  app-ui/lib/ui/mybook/mybook_list/mybook_list_screen.dart
  app-ui/lib/ui/mybook/mybook_screen.dart
  app-ui/lib/ui/profile/components/profile_header.dart
  app-ui/lib/ui/profile/follow/components/follow_user_info.dart
  app-ui/lib/ui/profile/follow/follow_screen.dart
  app-ui/lib/ui/profile/my_badge/my_badge_screen.dart
  app-ui/lib/ui/profile/profile_screen.dart
  app-ui/lib/ui/search/components/search_all_user_list.dart
  app-ui/lib/ui/search/components/search_popular_keyword.dart
  app-ui/lib/ui/search/search_screen.dart
  app-ui/lib/ui/setting/components/login_info.dart
  app-ui/lib/ui/setting/setting_screen.dart
Labels: feat, fix

#7 [IDLE-257] feat: 도서 상세보기 내 사용자 리스트 조회 페이지 구현
  app-ui/ios/Podfile
  app-ui/ios/Podfile.lock
  app-ui/lib/data/model/book/mybook_detail_response.dart
  app-ui/lib/data/model/search/book_detail_user_infos_model.dart
  app-ui/lib/data/model/search/book_detail_user_infos_model.g.dart
  app-ui/lib/data/provider/search/search_user_infos_provider.dart
  app-ui/lib/data/repository/search_new_repository.dart
  app-ui/lib/data/repository/search_new_repository.g.dart
  app-ui/lib/res/constants/enum.dart
  app-ui/lib/res/constants/style.dart
  app-ui/lib/ui/mybook/mybook_detail/components/mybook_detail_more.dart
  app-ui/lib/ui/mybook/mybook_detail/mybook_detail_screen.dart
  app-ui/lib/ui/profile/components/profile_intro.dart
  app-ui/lib/ui/search/components/search_all_user_list.dart
  app-ui/lib/ui/search/search_book_list/components/search_user_info.dart
  app-ui/lib/ui/search/search_book_list/components/search_user_layout.dart
  app-ui/lib/ui/search/search_book_list/search_book_list.dart
  app-ui/lib/ui/search/search_detail/components/book_detail_header.dart
  app-ui/lib/ui/search/search_detail_review/components/review_item.dart
  app-ui/lib/ui/search/search_detail_user_infos/components/user_count.dart
  app-ui/lib/ui/search/search_detail_user_infos/search_detail_user_infos_screen.dart
  app-ui/lib/utils/logics/common_utils.dart
Labels: feat
